apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vergunning-service.fullname" . }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secret.POSTGRES_USERNAME }}
  DB_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD }}
  CLIENT_SECRET: {{ .Values.secret.OAUTH_CLIENT_SECRET }}