apiVersion: v1
kind: Secret

metadata:
  name: external-dns-stackit
  namespace: external-dns

type: Opaque

stringData:
  STACKIT_SERVICE_ACCOUNT_KEY: |
    {
      "credentials": "replace-with-stackit-service-account-json"
    }