apiVersion: v1
kind: LimitRange
metadata:
  name: services-defaults
  namespace: services
spec:
  limits:
    - type: Container
      defaultRequest: # Automatically applied if the deployment omits 'requests'
        cpu: 250m
        memory: 512Mi
      default: # Automatically applied if the deployment omits 'limits'
        cpu: 750m
        memory: 1024Mi
      min:
        cpu: 50m
        memory: 128Mi
      max:
        cpu: "1"
        memory: 1Gi