apiVersion: v1
kind: ResourceQuota
metadata:
  name: services-quota
  namespace: services
spec:
  hard:
    # Compute
    requests.cpu: "2"
    limits.cpu: "4"

    requests.memory: 4Gi
    limits.memory: 8Gi

    # Objects
    pods: "10"
    services: "3"
    configmaps: "3"
    secrets: "3"

    # Storage
    persistentvolumeclaims: "1"
    requests.storage: "20Gi"