stages:
  - validate
  - build
  - test
  - security
  - package
  - publish
  - infrastructure

variables:
  SKIP_TEST: "true"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_TLS_CERTDIR: ""
  TF_ROOT: infrastructure/terraform
  STACKIT_REGISTRY: "$STACKIT_REGISTRY"
  STACKIT_REGISTRY_USER: "$STACKIT_REGISTRY_USER"
  STACKIT_REGISTRY_PASSWORD: "$STACKIT_REGISTRY_PASSWORD"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper
    - .gradle/caches

default:
  image: gradle:9.3.0-jdk25

before_script:
  - export DOCKER_HOST="tcp://docker:2375" # Needed for Testcontainers in CI
  - chmod -R +x gradle

###########################################################
# TERRAFORM
###########################################################

terraform-validate:
  stage: validate
  image:
    name: hashicorp/terraform:1.15.7
    entrypoint: [""]
  script:
    - cd ${TF_ROOT}
    - terraform init -backend=false
    - terraform validate

###########################################################
# BUILD
###########################################################

build:
  stage: build
  script:
    - gradle clean assemble
    - echo "Build."
  artifacts:
    expire_in: 1 week
    paths:
      - services/vergunning-service/build/libs/*.jar
      - services/zakenregistratie-service/build/libs/*.jar

###########################################################
# UNIT TESTS
###########################################################

test:
  stage: test
  rules:
    - if: $SKIP_TEST == "true"
      when: never
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - gradle test
    - gradle jacocoTestReport
  artifacts:
    reports:
      junit:
        - "**/build/test-results/test/*.xml"
    paths:
      - "**/build/reports/jacoco"

###########################################################
# INTEGRATION TESTS
###########################################################

integration-test:
  stage: test
  rules:
    - if: $SKIP_TEST == "true"
      when: never
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - gradle integrationTest

###########################################################
# BUILD CONTAINER IMAGES
###########################################################

publish-vergunning:
  stage: publish
  script:
    - cd services/vergunning-service
    - export IMAGE_NAME=${STACKIT_REGISTRY}/vergunning-service:${CI_COMMIT_SHA}
    - gradle jib
  only:
    - master

publish-zaken:
  stage: publish
  script:
    - cd services/zakenregistratie-service
    - export IMAGE_NAME=${STACKIT_REGISTRY}/zakenregistratie-service:${CI_COMMIT_SHA}
    - gradle jib
  only:
    - master

###########################################################
# HELM PACKAGE
###########################################################

helm-package:
  stage: package
  image:
    name: alpine/helm:3.17.3
    entrypoint: [""]
  script:
    - helm lint helm/vergunning-service
    - helm lint helm/zakenregistratie-service
    - helm package helm/vergunning-service
    - helm package helm/zakenregistratie-service
  artifacts:
    paths:
      - "*.tgz"

###########################################################
# TERRAFORM PLAN
###########################################################
terraform-plan:
  stage: infrastructure
  image:
    name: hashicorp/terraform:1.12
    entrypoint: [""]
  script:
    - cd ${TF_ROOT}
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - terraform/tfplan

###########################################################
# DEV DEPLOYMENT
###########################################################

deploy-dev:
  stage: publish
  environment:
    name: dev
  script:
    - echo "FluxCD reconciles deployment"
  only:
    - develop

###########################################################
# TEST DEPLOYMENT
###########################################################

deploy-test:
  stage: publish
  environment:
    name: test
  script:
    - echo "FluxCD reconciles deployment"
  only:
    - release/*

###########################################################
# PROD DEPLOYMENT
###########################################################

deploy-prod:
  stage: publish
  environment:
    name: production
  when: manual
  script:
    - echo "FluxCD reconciles deployment"
  only:
    - master