apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: vault

  target:
    name: keycloak-db-secret
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: keycloak/database
        property: username

    - secretKey: password
      remoteRef:
        key: keycloak/database
        property: password