apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "zakenregistratie-service.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zakenregistratie-service.fullname" . }}
      app.kubernetes.io/component: "backend"