apiVersion: v1
kind: Service
metadata:
  name: {{ include "zakenregistratie-service.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "zakenregistratie-service.fullname" . }}
    app.kubernetes.io/component: "backend"
  ports:
    - port: 8080
      targetPort: 8080
  type: {{ .Values.service.type }}