apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vergunning-service
  namespace: services
spec:
  interval: 1m
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./helm/vergunning-service/helm
      sourceRef:
        kind: GitRepository
        name: platform-gitops
        namespace: flux-system
  values:
    image:
      repository: agilesolutions/vergunning-service
      tag: 1.0.0
    service:
      port: 8080
    ingress:
      enabled: true
      className: nginx
      host: vergunning.local
