apiVersion: image.toolkit.fluxcd.io
kind: ImageUpdateAutomation
metadata:
  name: image-updates
  namespace: flux-system
spec:
  interval: 5m

  sourceRef:
    kind: GitRepository
    name: flux-system

  git:
    checkout:
      ref:
        branch: master

    commit:
      author:
        name: fluxcdbot
        email: robert.rong@agile-solutions.ch

      messageTemplate: |
        FluxCD Automated image update

        {{range .Changed.Changes}}
        - {{.OldValue}} -> {{.NewValue}}
        {{end}}

    push:
      branch: main

  update:
    path: ./cluster/apps
    strategy: Setters