# STACKIT Prometheus endpoints require authentication. Technical STACKIT credentials are created via STACKIT portal.
apiVersion: v1
kind: Secret
metadata:
  name: stackit-observability-keda
  namespace: services
type: Opaque
stringData:
  username: "<observability-username>"
  password: "<observability-password>"