apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloakx
  namespace: flux-system
spec:
  interval: 10m

  targetNamespace: keycloak
  install:
    createNamespace: true

  chart:
    spec:
      chart: keycloakx
      version: "7.1.9"
      sourceRef:
        kind: HelmRepository
        name: keycloakx
        namespace: flux-system
      interval: 5m

  values:

    command:
      - "/opt/keycloak/bin/kc.sh"
#      - "start"
      - "start-dev"
#      - "--http-port=8080"
#      - "--hostname=keycloak.local"
      - "--verbose"
#      - "--optimized"

    extraEnv: |
      - name: KEYCLOAK_ADMIN
        value: admin
      - name: KEYCLOAK_ADMIN_PASSWORD
        value: admin
      - name: KC_HEALTH_ENABLED
        value: "true"
#      - name: JAVA_OPTS_APPEND
#        value: >-
#          -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless

    replicas: 1

    # Startup probe configuration
    startupProbe: |
      httpGet:
        path: /auth/
        port: http
      initialDelaySeconds: 30
      timeoutSeconds: 120
      failureThreshold: 60
      periodSeconds: 120

    service:
      type: ClusterIP

    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: keycloak.local
          paths:
            - path: /
              pathType: Prefix

    postgresql:
      enabled: true

    http:
      port: 8080

    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"