
apiVersion: apps/v1
kind: Deployment
metadata:
  name: case-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: case-service
  template:
    metadata:
      labels:
        app: case-service
    spec:
      containers:
        - name: case-service
          image: ghcr.io/agilesolutions/demo:latest
          ports:
            - containerPort: 8080
