apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: stackit-observability
  namespace: services

spec:
  secretTargetRef:
    - parameter: username
      name: stackit-observability-keda
      key: username

    - parameter: password
      name: stackit-observability-keda
      key: password