
server:
  port: 8080


  application:
    name: vergunning-service

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: vergunning-service
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://keycloak/auth/realms/demo/protocol/openid-connect/token

