apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: zakenregistratie-service-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: zakenregistratie-service

  policy:
    semver:
      range: ">=1.0.0"